INSERT INTO "skills" ("slug", "display_name", "category", "difficulty") VALUES
('javascript', 'JavaScript', 'Frontend', 2),
('typescript', 'TypeScript', 'Frontend', 3),
('react', 'React', 'Frontend', 2),
('nextjs', 'Next.js', 'Frontend', 3),
('vuejs', 'Vue.js', 'Frontend', 2),
('angular', 'Angular', 'Frontend', 4),
('svelte', 'Svelte', 'Frontend', 2),
('tailwindcss', 'Tailwind CSS', 'Frontend', 1),
('html', 'HTML', 'Frontend', 1),
('css', 'CSS', 'Frontend', 2),
('redux', 'Redux', 'Frontend', 3),
('vite', 'Vite', 'Frontend', 2),
('webpack', 'Webpack', 'Frontend', 3),
('storybook', 'Storybook', 'Frontend', 2),
('nodejs', 'Node.js', 'Backend', 2),
('python', 'Python', 'Backend', 2),
('java', 'Java', 'Backend', 3),
('golang', 'Go', 'Backend', 3),
('rust', 'Rust', 'Backend', 5),
('php', 'PHP', 'Backend', 2),
('ruby', 'Ruby', 'Backend', 2),
('expressjs', 'Express.js', 'Backend', 2),
('nestjs', 'NestJS', 'Backend', 3),
('fastapi', 'FastAPI', 'Backend', 2),
('django', 'Django', 'Backend', 3),
('spring-boot', 'Spring Boot', 'Backend', 4),
('hono', 'Hono', 'Backend', 2),
('graphql', 'GraphQL', 'Backend', 3),
('rest-api', 'REST API', 'Backend', 2),
('csharp', 'C#', 'Backend', 3),
('dotnet', '.NET', 'Backend', 3),
('react-native', 'React Native', 'Mobile', 3),
('flutter', 'Flutter', 'Mobile', 3),
('swift', 'Swift', 'Mobile', 4),
('kotlin', 'Kotlin', 'Mobile', 3),
('expo', 'Expo', 'Mobile', 2),
('docker', 'Docker', 'DevOps', 3),
('kubernetes', 'Kubernetes', 'DevOps', 4),
('terraform', 'Terraform', 'DevOps', 4),
('github-actions', 'GitHub Actions', 'DevOps', 2),
('jenkins', 'Jenkins', 'DevOps', 3),
('helm', 'Helm', 'DevOps', 4),
('argocd', 'ArgoCD', 'DevOps', 4),
('linux', 'Linux', 'DevOps', 2),
('ansible', 'Ansible', 'DevOps', 3),
('nginx', 'Nginx', 'DevOps', 3),
('git', 'Git', 'DevOps', 2),
('aws', 'AWS', 'Cloud', 3),
('gcp', 'Google Cloud Platform', 'Cloud', 3),
('azure', 'Azure', 'Cloud', 3),
('firebase', 'Firebase', 'Cloud', 2),
('cloudflare', 'Cloudflare', 'Cloud', 2),
('vercel', 'Vercel', 'Cloud', 1),
('netlify', 'Netlify', 'Cloud', 1),
('supabase', 'Supabase', 'Cloud', 2),
('aws-lambda', 'AWS Lambda', 'Cloud', 3),
('cloud-run', 'Google Cloud Run', 'Cloud', 3),
('sql', 'SQL', 'Data', 2),
('postgresql', 'PostgreSQL', 'Data', 3),
('mysql', 'MySQL', 'Data', 2),
('mongodb', 'MongoDB', 'Data', 2),
('redis', 'Redis', 'Data', 3),
('elasticsearch', 'Elasticsearch', 'Data', 4),
('prisma', 'Prisma', 'Data', 2),
('drizzle-orm', 'Drizzle ORM', 'Data', 2),
('kafka', 'Apache Kafka', 'Data', 4),
('clickhouse', 'ClickHouse', 'Data', 4),
('sqlite', 'SQLite', 'Data', 1),
('jest', 'Jest', 'Testing', 2),
('vitest', 'Vitest', 'Testing', 2),
('cypress', 'Cypress', 'Testing', 2),
('playwright', 'Playwright', 'Testing', 3),
('react-testing-library', 'React Testing Library', 'Testing', 2),
('pytest', 'pytest', 'Testing', 2),
('selenium', 'Selenium', 'Testing', 3),
('k6', 'k6', 'Testing', 3),
('oauth', 'OAuth 2.0', 'Security', 3),
('jwt', 'JWT', 'Security', 2),
('tls-ssl', 'TLS/SSL', 'Security', 3),
('owasp', 'OWASP', 'Security', 3),
('figma', 'Figma', 'Design', 2),
('ux-design', 'UX Design', 'Design', 3),
('adobe-xd', 'Adobe XD', 'Design', 2),
('english', 'English', 'Language', 1),
('mandarin', 'Mandarin', 'Language', 5),
('spanish', 'Spanish', 'Language', 3),
('nepali', 'Nepali', 'Language', 3),
('hindi', 'Hindi', 'Language', 3),
('japanese', 'Japanese', 'Language', 5),
('french', 'French', 'Language', 3),
('arabic', 'Arabic', 'Language', 4),
('communication', 'Communication', 'Soft', 2),
('leadership', 'Leadership', 'Soft', 3),
('problem-solving', 'Problem Solving', 'Soft', 2),
('agile', 'Agile / Scrum', 'Soft', 2),
('project-management', 'Project Management', 'Soft', 3),
('mentoring', 'Mentoring', 'Soft', 3),
('critical-thinking', 'Critical Thinking', 'Soft', 2)
ON CONFLICT ("slug") DO UPDATE SET
	"display_name" = excluded."display_name",
	"category" = excluded."category",
	"difficulty" = excluded."difficulty",
	"updated_at" = now();
--> statement-breakpoint
INSERT INTO "skill_aliases" ("skill_id", "alias")
SELECT s."id", v."alias"
FROM (VALUES
('javascript', 'JS'),
('javascript', 'js'),
('javascript', 'Java Script'),
('javascript', 'ECMAScript'),
('javascript', 'ES6'),
('javascript', 'ES2015'),
('typescript', 'TS'),
('typescript', 'ts'),
('typescript', 'TypeScript'),
('react', 'ReactJS'),
('react', 'React.js'),
('react', 'React JS'),
('react', 'reactjs'),
('nextjs', 'Next.js'),
('nextjs', 'NextJS'),
('nextjs', 'Next JS'),
('nextjs', 'next.js'),
('vuejs', 'Vue'),
('vuejs', 'Vue.js'),
('vuejs', 'VueJS'),
('vuejs', 'Vue JS'),
('vuejs', 'vue'),
('angular', 'AngularJS'),
('angular', 'Angular.js'),
('angular', 'angular'),
('svelte', 'SvelteKit'),
('svelte', 'Svelte Kit'),
('tailwindcss', 'Tailwind'),
('tailwindcss', 'tailwind'),
('tailwindcss', 'Tailwind CSS'),
('tailwindcss', 'tailwind css'),
('html', 'HTML5'),
('html', 'html5'),
('html', 'Hyper Text Markup Language'),
('css', 'CSS3'),
('css', 'css3'),
('css', 'Cascading Style Sheets'),
('redux', 'Redux Toolkit'),
('redux', 'RTK'),
('redux', 'redux'),
('nodejs', 'Node.js'),
('nodejs', 'NodeJS'),
('nodejs', 'node'),
('nodejs', 'Node'),
('nodejs', 'Node JS'),
('nodejs', 'node.js'),
('python', 'Python3'),
('python', 'python3'),
('python', 'Python 3'),
('python', 'python'),
('java', 'Java SE'),
('java', 'Java EE'),
('java', 'JVM'),
('golang', 'Go'),
('golang', 'Go Lang'),
('golang', 'GoLang'),
('golang', 'Golang'),
('golang', 'go'),
('rust', 'Rust Lang'),
('rust', 'rust'),
('expressjs', 'Express'),
('expressjs', 'Express.js'),
('expressjs', 'ExpressJS'),
('expressjs', 'express'),
('nestjs', 'Nest.js'),
('nestjs', 'Nest JS'),
('nestjs', 'Nest'),
('nestjs', 'nest'),
('fastapi', 'Fast API'),
('fastapi', 'fast-api'),
('django', 'django'),
('django', 'Django REST Framework'),
('django', 'DRF'),
('spring-boot', 'Spring'),
('spring-boot', 'SpringBoot'),
('spring-boot', 'Spring Framework'),
('spring-boot', 'Spring MVC'),
('hono', 'hono'),
('hono', 'Hono.js'),
('graphql', 'GQL'),
('graphql', 'gql'),
('graphql', 'Graph QL'),
('graphql', 'GraphQL API'),
('rest-api', 'REST'),
('rest-api', 'RESTful'),
('rest-api', 'RESTful API'),
('rest-api', 'REST APIs'),
('rest-api', 'HTTP API'),
('csharp', 'C#'),
('csharp', 'c#'),
('csharp', 'CSharp'),
('csharp', 'C Sharp'),
('csharp', 'c sharp'),
('dotnet', '.NET'),
('dotnet', '.net'),
('dotnet', 'dotnet'),
('dotnet', 'ASP.NET'),
('dotnet', 'ASP.NET Core'),
('react-native', 'ReactNative'),
('react-native', 'RN'),
('react-native', 'React-Native'),
('flutter', 'flutter'),
('flutter', 'Flutter SDK'),
('swift', 'swift'),
('swift', 'Swift iOS'),
('kotlin', 'kotlin'),
('kotlin', 'Kotlin Android'),
('expo', 'Expo SDK'),
('expo', 'expo'),
('docker', 'docker'),
('docker', 'Docker Container'),
('docker', 'Docker Compose'),
('docker', 'Dockerfile'),
('kubernetes', 'K8s'),
('kubernetes', 'k8s'),
('kubernetes', 'k8S'),
('kubernetes', 'K8S'),
('kubernetes', 'kube'),
('kubernetes', 'Kube'),
('terraform', 'TF'),
('terraform', 'terraform'),
('terraform', 'HashiCorp Terraform'),
('github-actions', 'GitHub Actions'),
('github-actions', 'GH Actions'),
('github-actions', 'github actions'),
('github-actions', 'Github Actions CI'),
('jenkins', 'jenkins'),
('jenkins', 'Jenkins CI'),
('jenkins', 'Jenkins CI/CD'),
('helm', 'helm'),
('helm', 'Helm Charts'),
('helm', 'Helm Chart'),
('argocd', 'Argo CD'),
('argocd', 'Argo'),
('argocd', 'argo cd'),
('argocd', 'argocd'),
('linux', 'Linux OS'),
('linux', 'Unix'),
('linux', 'ubuntu'),
('linux', 'Ubuntu'),
('linux', 'Debian'),
('linux', 'CentOS'),
('linux', 'bash'),
('linux', 'Bash'),
('ansible', 'ansible'),
('ansible', 'Ansible Playbook'),
('nginx', 'nginx'),
('nginx', 'NGINX'),
('nginx', 'Nginx Web Server'),
('git', 'git'),
('git', 'Version Control'),
('git', 'Git VCS'),
('aws', 'Amazon Web Services'),
('aws', 'Amazon AWS'),
('aws', 'AWS Cloud'),
('gcp', 'Google Cloud'),
('gcp', 'GCP'),
('gcp', 'Google Cloud Platform'),
('gcp', 'Google GCP'),
('azure', 'Microsoft Azure'),
('azure', 'azure'),
('azure', 'Azure Cloud'),
('firebase', 'firebase'),
('firebase', 'Google Firebase'),
('firebase', 'Firebase Realtime'),
('firebase', 'Firestore'),
('supabase', 'supabase'),
('aws-lambda', 'Lambda'),
('aws-lambda', 'AWS Lambda Function'),
('aws-lambda', 'Serverless Functions'),
('aws-lambda', 'Serverless'),
('cloud-run', 'Cloud Run'),
('cloud-run', 'GCP Cloud Run'),
('cloud-run', 'Google Cloud Run'),
('sql', 'Structured Query Language'),
('sql', 'SQL Queries'),
('sql', 'RDBMS'),
('postgresql', 'Postgres'),
('postgresql', 'postgres'),
('postgresql', 'PSQL'),
('postgresql', 'psql'),
('postgresql', 'pg'),
('postgresql', 'Postgresql'),
('mysql', 'My SQL'),
('mysql', 'mysql'),
('mysql', 'MySQL DB'),
('mongodb', 'Mongo'),
('mongodb', 'mongo'),
('mongodb', 'MongoDB Atlas'),
('mongodb', 'Mongoose'),
('redis', 'redis'),
('redis', 'Redis Cache'),
('redis', 'Redis DB'),
('elasticsearch', 'Elastic'),
('elasticsearch', 'ELK'),
('elasticsearch', 'Opensearch'),
('elasticsearch', 'ElasticSearch'),
('prisma', 'Prisma ORM'),
('prisma', 'prisma'),
('prisma', 'Prisma Client'),
('drizzle-orm', 'Drizzle'),
('drizzle-orm', 'drizzle'),
('drizzle-orm', 'Drizzle ORM'),
('kafka', 'kafka'),
('kafka', 'Apache Kafka'),
('kafka', 'Kafka Streams'),
('kafka', 'Confluent Kafka'),
('jest', 'jest'),
('jest', 'Jest testing'),
('jest', 'Jest JS'),
('vitest', 'vitest'),
('vitest', 'Vite test'),
('cypress', 'cypress'),
('cypress', 'Cypress E2E'),
('cypress', 'Cypress.io'),
('playwright', 'playwright'),
('playwright', 'Playwright E2E'),
('playwright', 'Playwright testing'),
('react-testing-library', 'RTL'),
('react-testing-library', 'Testing Library'),
('react-testing-library', '@testing-library/react'),
('pytest', 'py.test'),
('pytest', 'PyTest'),
('pytest', 'Python testing'),
('selenium', 'selenium'),
('selenium', 'Selenium WebDriver'),
('selenium', 'Selenium Grid'),
('oauth', 'OAuth'),
('oauth', 'OAuth2'),
('oauth', 'OAuth 2.0'),
('oauth', 'Open Authorization'),
('jwt', 'Json Web Token'),
('jwt', 'JSON Web Token'),
('jwt', 'jwt'),
('jwt', 'JWT token'),
('figma', 'figma'),
('figma', 'Figma Design'),
('english', 'english'),
('english', 'English Language'),
('english', 'Business English'),
('nepali', 'nepali'),
('nepali', 'Nepalese'),
('nepali', 'Nepali Language'),
('nepali', 'नेपाली'),
('hindi', 'hindi'),
('hindi', 'Hindi Language'),
('hindi', 'हिन्दी'),
('mandarin', 'Chinese'),
('mandarin', 'Mandarin Chinese'),
('mandarin', '普通话'),
('mandarin', 'mandarin'),
('agile', 'Scrum'),
('agile', 'SCRUM'),
('agile', 'Kanban'),
('agile', 'Agile Methodology'),
('agile', 'agile'),
('agile', 'Agile/Scrum'),
('agile', 'Agile Scrum'),
('project-management', 'PM'),
('project-management', 'project management'),
('project-management', 'Technical Project Management'),
('problem-solving', 'Problem-Solving'),
('problem-solving', 'Problem Solving'),
('problem-solving', 'Analytical Thinking'),
('problem-solving', 'Analytical Skills'),
('leadership', 'Team Leadership'),
('leadership', 'Technical Leadership'),
('leadership', 'Tech Lead'),
('leadership', 'Engineering Leadership'),
('storybook', 'storybook'),
('storybook', 'Storybook.js'),
('sqlite', 'SQLite3'),
('sqlite', 'sqlite'),
('sqlite', 'SQLite DB')
) AS v("slug", "alias")
JOIN "skills" s ON s."slug" = v."slug"
ON CONFLICT ("alias") DO UPDATE SET
	"skill_id" = excluded."skill_id",
	"updated_at" = now();
