name: Lint and Test Workflow
on:
  push:
    branches:
      - main
      - features/*
  pull_request:
    branches:
      - main
jobs:
  lint-and-test:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: pnpm setup
        uses: pnpm/action-setup@v6
        with:
          version: 10
      - name: Install Dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm lint
